export type Project = {
    id: string;
    title: string;
    category: string;
    description: string;
    techStack: string[];
    repoUrl?: string;
    demoUrl?: string;
    image?: string;
    featured?: boolean;
    highlight: string;
    upcoming?: boolean;
    isProprietary?: boolean;
    isAcademic?: boolean;
};

export const projects: Project[] = [
    // --- Phase 1: Flagship AI & High-Performance Fabrics ---
    {
        id: "nexus-swarm",
        title: "Nexus Swarm",
        category: "AI / Agents",
        description: "Flagship stateful multi-agent system built on LangGraph. Operates as a Cyclical State Machine with Human-in-the-Loop authorization for autonomous research synthesis.",
        techStack: ["LangGraph", "Python", "FastAPI", "Next.js", "Pydantic"],
        repoUrl: "https://github.com/Kimosabey/nexus-swarm",
        image: "/projects/nexus-swarm/thumbnail.png",
        featured: true,
        highlight: "Orchestration: LangGraph",
    },
    {
        id: "vox-agent-neural",
        title: "VoxAgent Neural",
        category: "Neural Transcription",
        description: "High-fidelity real-time transcription engine with sub-second latency. Features an agentic control plane for deterministic neural inference pipelines.",
        techStack: ["FastAPI", "Faster-Whisper", "LiveKit", "WebSockets", "React"],
        repoUrl: "https://github.com/Kimosabey/vox-agent-neural",
        image: "/projects/vox-agent-neural/thumbnail.png",
        featured: true,
        highlight: "Latency: Sub-Second TAT",
    },
    {
        id: "live-nexus-ai",
        title: "LiveNexus AI",
        category: "Hybrid AI Transport",
        description: "Real-time hybrid audio intelligence platform. CPU-optimized inference nodes synchronized with distributed cloud transport for global vertical scaling.",
        techStack: ["Next.js 14", "LiveKit Cloud", "Faster-Whisper", "Docker", "Python"],
        repoUrl: "https://github.com/Kimosabey/live-nexus-ai",
        image: "/projects/live-nexus-ai/thumbnail.png",
        featured: true,
        highlight: "Architecture: Hybrid Cloud",
    },
    {
        id: "logstream-ai",
        title: "LogStream AI",
        category: "Observability",
        description: "Orchestrating high-volume log ingestion with autonomous anomaly detection. Utilizes batch-buffering protocols to stabilize extreme traffic spikes.",
        techStack: ["Go", "Elasticsearch", "Kibana", "Docker"],
        repoUrl: "https://github.com/Kimosabey/logstream-ai",
        image: "/projects/logstream-ai/thumbnail.png",
        highlight: "Ingest: Batch Buffering",
    },
    {
        id: "voicesync-ai",
        title: "VoiceSync AI",
        category: "Privacy / AI",
        description: "Hardened, offline-first audio transcription fabric. Executes Whisper model inference locally within the client viewport for 100% data sovereignty.",
        techStack: ["Electron", "Whisper.cpp", "React", "Local First"],
        repoUrl: "https://github.com/Kimosabey/voicesync-ai",
        image: "/projects/voicesync-ai/thumbnail.png",
        highlight: "Privacy: 100% Local Inference",
    },
    {
        id: "edge-matrix",
        title: "EdgeMatrix",
        category: "Distributed / AI",
        description: "High-performance Distributed Inference Engine. Orchestrates a matrix of edge nodes to execute massive AI models via layer sharding and WASM kernels.",
        techStack: ["Bun", "WebAssembly", "TypeScript", "WebSockets", "C++"],
        repoUrl: "https://github.com/Kimosabey/edge-matrix",
        image: "/projects/edge-matrix/thumbnail.png",
        featured: true,
        highlight: "Runtime: Bun & WASM",
    },
    {
        id: "limit-guard",
        title: "LimitGuard",
        category: "Security / Infra",
        description: "Distributed rate-limiting node for multi-layered DDoS mitigation. Implements precise Token Bucket and Leaky Bucket algorithmic constraints.",
        techStack: ["Redis/Lua", "Node.js", "Nginx", "System Design"],
        repoUrl: "https://github.com/Kimosabey/limit-guard",
        image: "/projects/limit-guard/thumbnail.png",
        highlight: "Algo: Token Bucket",
    },
    {
        id: "token-forge",
        title: "TokenForge",
        category: "Identity / Sec",
        description: "Hardened Identity Provider (IdP) with OIDC compliance. Features Redis-backed rate limiting, multi-factor biometric hooks, and automated key rotation.",
        techStack: ["NestJS", "OIDC/OAuth2", "Redis", "MFA/TOTP", "Docker"],
        repoUrl: "https://github.com/Kimosabey/token-forge",
        image: "/projects/token-forge/thumbnail.png",
        highlight: "Auth: OIDC & MFA",
    },
    {
        id: "chronicle-ledge",
        title: "ChronicleLedger",
        category: "Distributed Systems",
        description: "High-concurrency event sourcing ledger maintaining strict consistency (CP). Built with CockroachDB clusters and Raft consensus protocols.",
        techStack: ["Node.js", "CockroachDB", "NATS JetStream", "Event Sourcing", "Docker"],
        repoUrl: "https://github.com/Kimosabey/chronicle-ledger",
        image: "/projects/chronicle-ledge/thumbnail.png",
        featured: true,
        highlight: "Process: Raft Consensus",
    },
    {
        id: "order-saga",
        title: "OrderSaga",
        category: "Distributed Systems",
        description: "Reference implementation of the Distributed Saga Pattern. Orchestrates compensating transactions ensuring data consistency across microservices.",
        techStack: ["Node.js", "RabbitMQ", "PostgreSQL", "Next.js"],
        repoUrl: "https://github.com/Kimosabey/order-saga",
        image: "/projects/order-saga/thumbnail.png",
        highlight: "Pattern: Saga Choreography",
    },
    {
        id: "velocity-edge",
        title: "VelocityEdge",
        category: "High Performance",
        description: "High-throughput telemetry dashboard processing 100k+ events/sec. Optimized for sub-10ms latency using binary protocols and WebSocket streams.",
        techStack: ["Next.js", "WebSockets", "D3.js", "Redis", "Go"],
        repoUrl: "https://github.com/Kimosabey/velocity-edge",
        image: "/projects/velocity-edge/thumbnail.png",
        featured: true,
        highlight: "Speed: 100k Events/Sec",
    },
    {
        id: "data-quarantine",
        title: "DataQuarantine",
        category: "Data Engineering",
        description: "Fault-tolerant pipeline isolating malformed data packets. Integrates circuit breakers, dead letter queues, and automated re-sync mechanisms.",
        techStack: ["TypeScript", "Kafka", "PostgreSQL", "Prometheus", "Docker"],
        repoUrl: "https://github.com/Kimosabey/data-quarantine",
        image: "/projects/data-quarantine/thumbnail.png",
        featured: true,
        highlight: "Pattern: Circuit Breaker",
    },
    {
        id: "docmind-ai",
        title: "DocMind AI",
        category: "AI / RAG",
        description: "Advanced RAG (Retrieval-Augmented Generation) system for complex document siphoning. Utilizes hybrid semantic search and neural re-ranking.",
        techStack: ["Python", "LangChain", "OpenAI", "Pinecone", "Next.js"],
        repoUrl: "https://github.com/Kimosabey/docmind-ai",
        image: "/projects/docmind-ai/thumbnail.png",
        highlight: "Flow: Hybrid Search",
    },
    {
        id: "agent-core",
        title: "Agent Core",
        category: "AI / Agents",
        description: "Autonomous neural agent framework implementing the ReAct protocol. Capable of systematic tool use, memory persistence, and multi-step reasoning.",
        techStack: ["Python", "Ollama", "Chromadb", "Local LLMs"],
        repoUrl: "https://github.com/Kimosabey/agent-core",
        image: "/projects/agent-core/thumbnail.png",
        highlight: "Model: ReAct Pattern",
    },
    {
        id: "speak-flow",
        title: "SpeakFlow",
        category: "Voice Tech",
        description: "Real-time acoustic analysis tool for phonetic accuracy. Visualizes voice waveforms and scores performance using low-level browser Audio APIs.",
        techStack: ["React", "Web Audio API", "Framer Motion", "Vite"],
        repoUrl: "https://github.com/Kimosabey/speak-flow",
        image: "/projects/speak-flow/thumbnail.png",
        highlight: "Audio: Real-time FFT",
    },
    {
        id: "spec-lens",
        title: "SpecLens",
        category: "DevTools",
        description: "Automated API specification auditing node. Lints OpenAPI/Swagger schemas for security vulnerabilities and architectural style guide violations.",
        techStack: ["TypeScript", "AST", "React", "OpenAPI"],
        repoUrl: "https://github.com/Kimosabey/spec-lens",
        image: "/projects/spec-lens/thumbnail.png",
        highlight: "Parse: AST Analysis",
    },
    {
        id: "inference-hub",
        title: "InferenceHub",
        category: "ML Ops",
        description: "Centralized model serving grid. Manages versioned neural deployments, A/B testing protocols, and exposes a unified inference core.",
        techStack: ["FastAPI", "Docker", "Kubernetes", "MLflow"],
        repoUrl: "https://github.com/Kimosabey/inference-hub",
        image: "/projects/inference-hub/thumbnail.png",
        highlight: "Deploy: A/B Testing",
    },

    // --- Phase 2: Proprietary Industrial Deployments ---
    {
        id: "tabedaar",
        title: "Tabedaar Service",
        category: "E-Commerce / Logistics",
        description: "Orchestrating an all-in-one service provider platform featuring high-density CMS modules for admin control, merchant telemetry, rider management, and real-time order processing.",
        techStack: ["React", "Java", "MSSQL", "RESTful Web Svcs"],
        highlight: "Multi-Node Logistics",
        isProprietary: true,
    },
    {
        id: "canada-bizzsp",
        title: "Canada Bizzsp App",
        category: "Media Architecture",
        description: "Developing a short-video business application ecosystem. Manifested CMS functionality for complex content siphoning and global application maintenance protocols.",
        techStack: ["React", "React Native", "Java", "MSSQL"],
        highlight: "Video Content Siphon",
        isProprietary: true,
    },
    {
        id: "zeus-biotech",
        title: "Zeus Biotech",
        category: "Enterprise CMS",
        description: "Engineering a specialized CMS core for biotechnology management. Synchronizing orders, customer distributors, and internal business workflows into a unified data environment.",
        techStack: ["React", "Node.js", "MSSQL", "REST APIs"],
        highlight: "Data Normalization",
        isProprietary: true,
    },

    // --- Phase 3: Academic Research & Legacy Nodes ---
    {
        id: "graphical-captcha",
        title: "Captcha as Graphical Password",
        category: "Post Graduate Project (MCA)",
        description: "Developed a security-focused authentication mechanism using graphical captcha. Orchestrated with .NET Framework 4.0 in Visual Studio 2015 for high-integrity login nodes.",
        techStack: ["C#", "Python", "ASP.NET (C#)", "MySQL", ".NET 4.0"],
        highlight: "2019 – 2020 | MCA Core",
        isAcademic: true,
    },
    {
        id: "early-reviewer-predict",
        title: "Characterizing Early Reviewers",
        category: "Undergraduate Project (BCA)",
        description: "Built a data-driven system to identify and predict early reviewers for optimized product marketing. Engineered via C# and MySQL in Visual Studio 2015 environment.",
        techStack: ["C#", "MySQL", "Data Mining", "Predictive ML"],
        highlight: "2018 – 2019 | BCA Core",
        isAcademic: true,
    },
    {
        id: "chit-fund-sys",
        title: "Chit Fund System",
        category: "Legacy / FinTech",
        description: "Standalone legacy ledger for managing complex financial schemes. Manifests high-accuracy interest calculation engines and member management filaments.",
        techStack: ["JSP/Servlets", "SQL Server", "MVC"],
        highlight: "Logic: Complex Engines",
        isProprietary: true,
    },

    // --- Phase 4: Forthcoming Neural Subsystems (The Lab) ---
    {
        id: "lakehouse-pro",
        title: "Lakehouse Pro",
        category: "Big Data / Java",
        description: "Enterprise-grade real-time IoT telemetry pipeline. Leverages the Medallion Architecture with Kafka and ClickHouse for sub-second analytics over millions of events.",
        techStack: ["Java (Spring)", "ClickHouse", "Kafka", "Protobuf", "Node.js"],
        repoUrl: "https://github.com/Kimosabey/lakehouse-pro",
        image: "/projects/lakehouse-pro/thumbnail.png",
        highlight: "Data: High Throughput",
    },
    {
        id: "ring-route",
        title: "RingRoute",
        category: "Distributed / Go",
        description: "High-concurrency request router utilizing Consistent Hashing rings. Ensures zero-rebalancing node stability for stateful distributed workloads.",
        techStack: ["Go (Fiber)", "Consistent Hashing", "gRPC"],
        repoUrl: "https://github.com/Kimosabey/ring-route",
        image: "/projects/ring-route/thumbnail.png",
        highlight: "Algo: Consistent Hash",
    },
];
